version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_topaz
    environment:
      POSTGRES_DB: tarefas
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./todo_list_topaz
    container_name: backend_topaz
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./todo_list_topaz_front
    container_name: frontend_topaz
    ports:
      - "3000:80"
